export enum AuditEventType {
  // Auth Events
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_MFA_ENABLED = 'AUTH_MFA_ENABLED',
  AUTH_MFA_VERIFIED = 'AUTH_MFA_VERIFIED',
  AUTH_MFA_FAILED = 'AUTH_MFA_FAILED',
  AUTH_PASSWORD_RESET_REQ = 'AUTH_PASSWORD_RESET_REQ',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS',
  AUTH_SESSION_REVOKED = 'AUTH_SESSION_REVOKED',
  AUTH_ALL_SESSIONS_REVOKED = 'AUTH_ALL_SESSIONS_REVOKED',

  // User & Role Events
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  ROLE_PERMISSION_CHANGED = 'ROLE_PERMISSION_CHANGED',

  // Security Events
  SECURITY_RATE_LIMIT_TRIGGERED = 'SECURITY_RATE_LIMIT_TRIGGERED',
  SECURITY_SUSPICIOUS_ACTIVITY = 'SECURITY_SUSPICIOUS_ACTIVITY',

  // Catalog & Inventory Events
  CATALOG_PRODUCT_CREATED = 'CATALOG_PRODUCT_CREATED',
  CATALOG_PRODUCT_UPDATED = 'CATALOG_PRODUCT_UPDATED',
  CATALOG_PRODUCT_DELETED = 'CATALOG_PRODUCT_DELETED',
  INVENTORY_ADJUSTED = 'INVENTORY_ADJUSTED',

  // Commerce & Finance Events
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUND_APPROVED = 'REFUND_APPROVED',
  CURRENCY_RATE_UPDATED = 'CURRENCY_RATE_UPDATED',
  PRICE_OVERRIDE_UPDATED = 'PRICE_OVERRIDE_UPDATED',
  PRICE_OVERRIDE_DELETED = 'PRICE_OVERRIDE_DELETED',
  PROMOTION_CREATED = 'PROMOTION_CREATED',
  PROMOTION_DELETED = 'PROMOTION_DELETED',
  TAX_RULE_UPDATED = 'TAX_RULE_UPDATED',
  CONCIERGE_INQUIRY_UPDATED = 'CONCIERGE_INQUIRY_UPDATED',
  BESPOKE_REQUEST_UPDATED = 'BESPOKE_REQUEST_UPDATED',

  // CMS & Media Events
  CMS_PAGE_CREATED = 'CMS_PAGE_CREATED',
  CMS_PAGE_UPDATED = 'CMS_PAGE_UPDATED',
  CMS_PAGE_DELETED = 'CMS_PAGE_DELETED',
  HERO_BANNER_CREATED = 'HERO_BANNER_CREATED',
  HERO_BANNER_UPDATED = 'HERO_BANNER_UPDATED',
  HERO_BANNER_DELETED = 'HERO_BANNER_DELETED',
  MEDIA_ASSET_UPLOADED = 'MEDIA_ASSET_UPLOADED',
  MEDIA_ASSET_DELETED = 'MEDIA_ASSET_DELETED',
}

export interface AuditLogDto {
  id: string;
  eventType: AuditEventType;
  userId?: string | null;
  userEmail?: string | null;
  userRole?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  resourceType?: string | null;
  resourceId?: string | null;
  metadata?: Record<string, any> | null;
  createdAt: string;
}
