'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ShieldAlert, ArrowLeft, KeyRound, AlertTriangle } from 'lucide-react';
import { apiRequest } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';

export default function MfaVerifyPage() {
  const router = useRouter();
  const { loginSuccess } = useAuth();

  const [code, setCode] = useState('');
  const [mfaToken, setMfaToken] = useState<string | null>(null);
  const [email, setEmail] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    const token = sessionStorage.getItem('tbh_mfa_token');
    const storedEmail = sessionStorage.getItem('tbh_mfa_email') || 'your account';
    if (!token) {
      router.push('/login');
    } else {
      setMfaToken(token);
      setEmail(storedEmail);
    }
  }, [router]);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!mfaToken) return;

    setIsLoading(true);
    setErrorMessage(null);

    try {
      const response = await apiRequest('/admin/auth/mfa/verify', {
        method: 'POST',
        data: { mfaToken, code },
      });

      sessionStorage.removeItem('tbh_mfa_token');
      sessionStorage.removeItem('tbh_mfa_email');

      if (response.accessToken && response.user) {
        loginSuccess(response.user, response.accessToken);
      }
    } catch (err: any) {
      setErrorMessage(
        err.message || 'Invalid or expired authentication code. Please try again.',
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-obsidian-950 px-4 py-12">
      <div className="relative w-full max-w-md">
        <div className="text-center mb-8">
          <div className="inline-flex h-16 w-16 items-center justify-center rounded-2xl border border-gold-500/30 bg-gold-500/10 shadow-xl shadow-gold-500/10 mb-4">
            <ShieldAlert className="h-8 w-8 text-gold-400" />
          </div>
          <h1 className="font-serif text-3xl font-bold tracking-wider text-slate-100">
            TWO-FACTOR VERIFICATION
          </h1>
          <p className="mt-1 text-xs font-semibold uppercase tracking-widest text-gold-400">
            HIGH-SECURITY STEP-UP
          </p>
        </div>

        <div className="rounded-2xl border border-obsidian-700 bg-obsidian-900/90 p-8 shadow-2xl backdrop-blur-xl">
          <p className="text-xs text-slate-300 text-center mb-6 leading-relaxed">
            Enter the 6-digit verification code generated by your Authenticator app for{' '}
            <span className="font-semibold text-gold-300">{email}</span>.
          </p>

          {errorMessage && (
            <div className="mb-6 flex items-start space-x-3 rounded-lg border border-red-500/30 bg-red-500/10 p-3.5 text-xs text-red-300">
              <AlertTriangle className="h-4 w-4 shrink-0 text-red-400 mt-0.5" />
              <span>{errorMessage}</span>
            </div>
          )}

          <form onSubmit={handleVerify} className="space-y-4">
            <div>
              <label className="block text-xs font-medium uppercase tracking-wider text-slate-400 mb-2 text-center">
                6-Digit Security Code
              </label>
              <div className="relative">
                <KeyRound className="absolute left-3.5 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-500" />
                <input
                  type="text"
                  maxLength={6}
                  autoFocus
                  required
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                  placeholder="000 000"
                  className="w-full rounded-lg border border-obsidian-750 bg-obsidian-950 py-3 pl-12 pr-4 text-center font-mono text-xl tracking-[0.3em] text-gold-300 placeholder-slate-600 focus:border-gold-500 focus:outline-none focus:ring-1 focus:ring-gold-500/40"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={isLoading || code.length < 6}
              className="mt-6 flex w-full items-center justify-center space-x-2 rounded-lg border border-gold-500/60 bg-gradient-to-r from-gold-600 to-gold-500 py-3 text-xs font-bold uppercase tracking-widest text-obsidian-950 shadow-lg shadow-gold-500/20 transition hover:from-gold-500 hover:to-gold-400 active:scale-[0.99] disabled:opacity-50"
            >
              {isLoading ? (
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-obsidian-950 border-t-transparent" />
              ) : (
                <span>Confirm & Authorize</span>
              )}
            </button>
          </form>

          <div className="mt-6 text-center">
            <Link
              href="/login"
              className="inline-flex items-center space-x-2 text-xs text-slate-400 hover:text-slate-200 transition"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              <span>Back to Login</span>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
